### ISSUE TITLE
Wrong import statements in examples on README.md

### ISSUE THREAD

**Issue by fuwaraido** [dallonf/react-stable-uniqueid#7]
I installed latest packaged from npm 8.5.0 today. It installed the package under react-stable-uniqueid dierctory. So I guess, import statement should be:

`import { useStableUniqueId } from 'react-stable-uniqueid';`

but in README.md, import statement is:

`import { useStableUniqueId } from 'react-stable-unique-id';`

I guess it's spelling mistake...I'm using react on next.js. So maybe that's because of my environment or something though...

**Comment by dallonf** [comment]
Good catch, thanks! Just updated the README with the correct name.
